### ISSUE TITLE
Errors reported by slivar and no variants 

### ISSUE THREAD

**Issue by lindakjcao** [brentp/slivar#139]
Hi Brent,

I used this cmd line
slivar/0.2.7/slivar expr \
  --vcf vep.norm.vcf \
   \
  --ped ../F0002.ped \
  --alias F0002.slivar.alias \
  --js slivar/filters.js \
   \
  --info "impact:includes_filter(INFO, VCF.CSQ, 'CONSEQUENCE', ['missense', 'splice_donor_variant', 'frameshift', 'inframe', 'stop', 'start'])" \
  --out-vcf impact.vcf

Our VCF is annotated with VEP v106.0.

And here is the msg with a lot of warnings that requested to report to you.
[slivar] Finished. evaluated 604603 total variants and wrote 0 variants that passed your slivar expressions.

The msg is long, but mostly about 3 splice related terms from VEP, for each type, I picked one warning here for your reference:

warning: unknown impact "splice_polypyrimidine_tract" from csq "A|splice_polypyrimidine_tract_variant&intron_variant&non_coding_transcript_variant|LOW|WASH7P|653635|Transcript|NR_024540.1|transcribed_pseudogene||5/10||||||||||-1||EntrezGene||||G|G|OK|||||||||||||||COSV70830160&COSV70830160|4&4|||0.00400000018998981|1.15299999713898" please report the variant at https://github.com/brentp/slivar/issues

warning: unknown impact "splice_donor_region" from csq "C|splice_donor_region_variant&intron_variant&non_coding_transcript_variant|LOW|CROCCP2|84809|Transcript|NR_026752.1|transcribed_pseudogene||5/6||||||||||-1||EntrezGene||||T|T||||||||||||||||COSV62931190|6|||0.0199999995529652|0.140000000596046" please report the variant at https://github.com/brentp/slivar/issues

warning: unknown impact "splice_donor_5th_base" from csq "-|splice_donor_5th_base_variant&intron_variant&non_coding_transcript_variant|LOW|BAGE2|85319|Transcript|NR_169269.1|lncRNA||1/12||||||||||1||EntrezGene||||GATGGCGGCTG|GATGGCGGCTG|||||||||||||||||||||" please report the variant at https://github.com/brentp/slivar/issues

Thank you.
Linda

**Comment by lindakjcao** [comment]
oops, we figured it out.  We used older version of filters.js.  We updated the js and now its working.

**Comment by brentp** [comment]
Hi Linda,
you can see more about the unknown consequences here: https://github.com/brentp/slivar/issues/118
I will get those added to the default impact order for the next release, but meanwhile, you can specify them yourself as indicated in that issue.
Those are just warnings.

The reason you are not getting any passing variants is because nothing is passing your filter: `includes_filter`. Can you show the source of that javascript function? You can do something like this using: https://github.com/brentp/slivar/wiki/impactful#infohighest_impact_order
just check that against each of your impacts.
