### ISSUE TITLE
support CSQ

### ISSUE THREAD

**Issue by brentp** [brentp/slivar#3]
converting CSQ to a usable object via the js expressions would be useful. the most useful part of this is the missense/gene impact stuff which is provided by bcftools CSQ. If that has an API, it would be nice to simply use that and not require the user to annotate.

**Comment by genomics-geek** [comment]
It would be great if CSQ could be a usable object via expressions. 

Would make it so easy to build JavaScript functions that can use that object for more custom/advanced filtering.

Even if the VCF header was accessible in the expressions. That would help determine the order of elements in that field.

**Comment by brentp** [comment]
hi, I am trying to avoid this. instead, I have exposed `INFO.impactful`. does this satisfy your needs? 
https://github.com/brentp/slivar/wiki/impactful

if not, you have access to CSQ as INFO.CSQ and could potentially write some javascript classes to make accessing that nicer. I can expose the order of fields from the header, if that does really help.

**Comment by genomics-geek** [comment]
Hi @brentp, not really.  Annotating with VEP adds some of the custom annotations to the `CSQ` field.  I was hoping to write some javascript to filter on some of those values.  

Currently, since we always annotate with the same tools, I know the order.  But I just worry that if we add a new annotation and don't adjust the filters, it could be using the wrong data.  It would be nice to infer the order from the header rather than having to "hardcode" it.

Example:
```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|REFSEQ_MATCH|GIVEN_REF|USED_REF|BAM_EDIT|SOURCE|CLIN_SIG|SOMATIC|PHENO|PUBMED|HGMD|HGMD_CLASS|COSMIC|COSMIC_CLNSIG|ClinVar|ClinVar_CNT|gnomad_pli|gnomad_missense_z">
```

```
CSQ=T|missense_variant|MODERATE|SCNN1D|6339|Transcript|NM_001130413.3|protein_coding|16/18||||2180|1954|652|P/S|Ccg/Tcg|rs113608779||1||EntrezGene|||C|C|OK||||||||COSM7388960&COSM7388961||||1.6507e-33|-7.8105e-01,T|non_coding_transcript_exon_variant|MODIFIER|SCNN1D|6339|Transcript|NR_037668.2|misc_RNA|15/17||||2086|||||rs113608779||1||EntrezGene|||C|C|OK||||||||COSM7388960&COSM7388961||||1.6507e-33|-7.8105e-01
```

If in the expressions CSQ was an object with key refering to the value that would be great. If not, just being able to somehow access the VCF header info line, then I could pass that info to the filter and be able to map the fields.

**Comment by brentp** [comment]
ok. let me think about this. it won't be for a few weeks, but I think having an opt-in way to access the CSQ could be do-able.
Given the CSQ you show above, what are you filtering on?

**Comment by genomics-geek** [comment]
awesome. That would be great!

Filter on:
+ `HGMD_CLASS`
+ `ClinVar_CLINSIG`
+ `gnomad_pli `
etc

**Comment by asapb** [comment]
Hi there,

I'm running the latest version of slivar v.01.6 (MD5 checksum 191af33e16a423847caa7fc572216806) with the `slivar expr` and the `--group-expr` option.

I'm getting output (extracting variants), but for each run I am also getting CSQ errors (please see example below):

```
error: unknown impact "" from csq "|GGCGGC/GGCGGCGGC|GG/GGG|ENSG00000169083|AR|ENST00000374690|1/8|||457-458/920|protein_coding|YES|Transcript|1893-1898/10065|1369-1374/2763|||1||||||||||||ENST00000374690.3:c.1369_1374delGGCGGCinsGGCGGCGGC|ENSP00000363822.3:p.Gly458dup" please report the variant at https://github.com/brentp/slivar/issues
```

My slivar command looks like this:

```
info="variant.FILTER == 'PASS'"
gnotation=gnomad.hg37.zip # Downloaded from the slivar GitHub website
pair=normalID_vs_otherID
alias=pair.grp  # group definition

$SRC/bin/slivar expr \
        --pass-only \
        --vcf $vcf \
        --out-vcf $out \
        --gnotate $gnotation \
        --alias $alias \
        --info "$info" \
        --group-expr "${pair}:normal.alts !== other.alts"
```

where 

**`pair.grp`**
```
#normal	other
normalID	otherID
```

No pedigree file because there's no known relationship between the samples.

Am getting many more of those errors due to unknown impact from csq.
Just posting one example here.

What is this due to and what does it mean?

Many thanks,
Åsa

**Comment by brentp** [comment]
can you share the VEP CSQ header line for that file? and is it a recent VEP version?

**Comment by genomics-geek** [comment]
Hi @brentp, what is the recommended way to filter for fields in CSQ?  

Since VEP puts fields in a | delimited CSQ field, I’ve been writing js expressions to split CSQ and find the position in the list to then filter against. 

Are their plan to make CSQ and object or at least make the header accessible?  I was just trying to find a way to know how the CSQ field is organized within js expressions.

**Comment by brentp** [comment]
hi, I implemented `INFO.impactful` to simplify this as much as possible. with that, a variant is either of interest or not. 
you can always write a javascript function that takes INFO.CSQ, splits, and gives you easy access to the fields. I haven't seen a concrete enough use-case that can't be more easily handled by `impactful`, and it's hard to work reliably with the other fields because sometimes they are numbers (which are sometimes absent so CSQ.gnomad_pli > 0.95 won't work), and sometimes they are string are sometimes empty. if you can write and share a javascript function that handles what you need, then I could see how that could be included into slivar (which would improve performance).

**Comment by brentp** [comment]
> I was just trying to find a way to know how the CSQ field is organized within js expressions.

I'll see if I can make this available in a useful way.

**Comment by genomics-geek** [comment]
@brentp yup I completely get it.  I understand why it is a challenge because the CSQ in VCF is not typed.

I guess if there was some way to at least get at the order from the VCF header:

`##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|REFSEQ_MATCH|GIVEN_REF|USED_REF|BAM_EDIT|SOURCE|HGMD|HGMD_CLASS|COSMIC|COSMIC_CNT|ClinVar|ClinVar_CLNSIG|gnomad_pli|gnomad_missense_z|GERP|phastCons|phyloP">`

Then the functions we write can just deal with type coercion. At the moment, I find myself "hard coding" the order of the CSQ and hoping it doesn't change.  If I had a way to know how to safely always access the `phastCons` value from INFO.CSQ, that would be a huge help. Does that make sense?

**Comment by brentp** [comment]
yes, and given a header like that, as of latest release, you'll have access to `VCF.CSQ` which will look like `["ALLELE", "CONSEQUENCE", "IMPACT", "SYMBOL", ...]` for your header. so you can use that to know the order.

**Comment by genomics-geek** [comment]
Nice, this is perfect.  So in the js functions we can access VCF? If so, I will check out the latest release - this should really simplify what I have been doing.  Thanks!

**Comment by brentp** [comment]
> So in the js functions we can access VCF?

yes

**Comment by genomics-geek** [comment]
@brentp - tested it out, this is perfect.  Makes my filters way easier to maintain.  Thanks for adding this!

**Comment by brentp** [comment]
I think this is enough functionality that users can write their own javascript for CSQ stuff.

**Comment by zihhuafang** [comment]
Hi @brentp,

I am new to java so difficult to see how to write a function to filter based on CSQ field.
Would you mind to provide an example?

For instance, I have a VEP CSQ field as the following:
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation">

If I want to filter based on "SYMBOL", which is SYMBOL= a list of the gene symbols, how should I write the function and put the command in slivar expr?

Thank you in advance.

**Comment by brentp** [comment]
Hi, sorry for the delay, this would be quite involved, but certainly possible, you can do, e.g.:
```
var parts = INFO.CSQ.split(/,/);
for(part in parts) {
    let sp = part.split(/\|/)
    if( gene_list.has(sp[1])) {
      return true; // or do soemthing else with this
   }
}
```
so it's possible, but better to filter to a genelist using a bed file of regions and `slivar expr --region $bed_file ... `
