### ISSUE TITLE
Support for annotations in table format

### ISSUE THREAD

**Issue by edg1983** [brentp/slivar#49]
Hi,

Any plan to add support for annotations coming in a table format so that they can also be converted to gnotate format and used during variant filtering?
Indeed, several genome-wide mutation impact predictions come in tab-separated files.

I appreciate that we can annotate the file before with vcfanno and then filter with slivar using the pre-annotated fields, but annotation with slivar is faster and could be convenient to do the whole process in a single step.

**Comment by brentp** [comment]
i understand why this would be useful, but i don't intend to add--mostly so `slivar` doesn't get so complex that i can't maintain (but also so that users can't use it)
originally, slivar wasn't going to have the gnotation piece, but annotating with gnomad as so critical for rare-disease stuff that I had to add it. I don't want to push that to far as vcfanno (which is quite good IMO) has shown how hard it is for me to maintain and users to understand when all use-cases are supported. plus, the main advantage of slivar gnotation (speed) is only realized on huge datasets like gnomad.

that said, it's possible to convert any tab-delimited file into a VCF and then use `make-gnotate` to convert it to a gnotation zip file.
